name: Build and Push to Docker Hub

on:
  push:
    branches: [ "master" ] # Проверьте, что тут именно master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          # Прописываем логин текстом, а пароль берем из секретов
          username: antoshkaman
          password: ${{ secrets.DOCKER_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Здесь тоже прописываем ваше имя пользователя вручную
          tags: antoshkaman/schedulebotik:latest
